#!/usr/bin/env ruby
require 'rake'
require 'pry'

require_relative './lib/raccumber/step_definitions'
require_relative './lib/raccumber/feature_scanner'
require_relative './lib/raccumber/feature_parser'

step_definition_files = FileList.new "features/**/*.rb"

step_definition_files.each do |s|
  load s
end

feature_files = FileList.new "features/**/*.feature"

fs = FeatureScanner.new

features = []

feature_files.each do |f|
  text = File.read f
  scenarios = fs.tokenize text
  features = Raccumber::FeatureParser.new.parse scenarios
  puts features.inspect
end
