#!/usr/bin/env ruby
require 'rake'
require 'pry'

$LOAD_PATH.unshift "lib"

require 'raccumber/step_definitions'
require 'raccumber/feature_scanner'
require 'raccumber/feature_parser'

step_definition_files = FileList.new "features/**/*.rb"

step_definition_files.each do |s|
  load s
end

feature_files = FileList.new "features/**/*.feature"

fs = FeatureScanner.new

features = []

feature_files.each do |f|
  text = File.read f
  scenarios = fs.tokenize text
  features << Raccumber::FeatureParser.new.parse(scenarios).first
end

results = features.inject([0,0,0]) do |m, f|
  m.zip(f.evaluate).map {|a, b| a + b }
end

puts "#{results[0]} successes, #{results[1]} failures, #{results[2]} undefined"
