#!/usr/bin/env ruby
require 'rake'

require_relative './lib/raccumber/step_definitions'
require_relative './lib/raccumber/feature_scanner'

step_definition_files = FileList.new "features/**/*.rb"

step_definition_files.each do |s|
  load s
end

features = FileList.new "features/**/*.feature"

fs = FeatureScanner.new

features.each do |f|
  text = File.read f
  scenarios = fs.tokenize text
  puts scenarios.inspect
end
