#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Raccumber
  class FeatureParser < Racc::Parser

module_eval(<<'...end feature_parser.racc/module_eval...', 'feature_parser.racc', 23)

def parse(tokens)
  @tokens = tokens
  do_parse
end

def next_token
  @tokens.shift
end
...end feature_parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
     3,     4,     6,     7,     8,     9,    11,    13,    14,     6,
    16,    13 ]

racc_action_check = [
     0,     1,     2,     3,     4,     6,     7,     9,    10,    12,
    13,    16 ]

racc_action_pointer = [
    -2,     1,    -2,     0,     4,   nil,     2,     3,   nil,     2,
     5,   nil,     5,     7,   nil,   nil,     6,   nil ]

racc_action_default = [
   -11,   -11,    -1,   -11,   -11,    -2,   -11,    -3,    18,   -11,
    -4,    -5,    -8,   -11,    -6,    -7,    -9,   -10 ]

racc_goto_table = [
     5,    12,     2,    10,     1,   nil,   nil,   nil,    17,   nil,
    15 ]

racc_goto_check = [
     3,     5,     2,     4,     1,   nil,   nil,   nil,     5,   nil,
     3 ]

racc_goto_pointer = [
   nil,     4,     2,    -2,    -4,    -8 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 7, :_reduce_none,
  2, 7, :_reduce_none,
  2, 8, :_reduce_none,
  3, 8, :_reduce_none,
  1, 10, :_reduce_none,
  2, 10, :_reduce_none,
  4, 9, :_reduce_none,
  3, 9, :_reduce_none,
  2, 11, :_reduce_none,
  3, 11, :_reduce_none ]

racc_reduce_n = 11

racc_shift_n = 18

racc_token_table = {
  false => 0,
  :error => 1,
  :FEAT_KEYWORD => 2,
  :TEXT => 3,
  :SCEN_KEYWORD => 4,
  :STEP_KEYWORD => 5 }

racc_nt_base = 6

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "FEAT_KEYWORD",
  "TEXT",
  "SCEN_KEYWORD",
  "STEP_KEYWORD",
  "$start",
  "feature",
  "feature_title",
  "scenario",
  "description",
  "step_definition" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class FeatureParser
  end   # module Raccumber
